"""tg model updates

Revision ID: 0af31f018cbc
Revises: cc0ddd888212
Create Date: 2026-02-18 14:57:14.401363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af31f018cbc'
down_revision: Union[str, Sequence[str], None] = 'cc0ddd888212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_link_tokens', sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_link_tokens', 'expires_at')
    # ### end Alembic commands ###
