"""models tweaked

Revision ID: 10d3c13beff5
Revises: 0312cb0c5d65
Create Date: 2026-02-04 20:10:42.570817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d3c13beff5'
down_revision: Union[str, Sequence[str], None] = '0312cb0c5d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sites_user_name', 'sites', ['user_id', 'name'])
    op.create_unique_constraint('uq_sites_user_url', 'sites', ['user_id', 'url'])
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('email_verified_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_confirm_token_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('email_confirm_expires_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirm_expires_at')
    op.drop_column('users', 'email_confirm_token_hash')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'is_verified')
    op.drop_constraint('uq_sites_user_url', 'sites', type_='unique')
    op.drop_constraint('uq_sites_user_name', 'sites', type_='unique')
    # ### end Alembic commands ###
