"""additional db indexes

Revision ID: 4b78124fbad8
Revises: f0993537e247
Create Date: 2026-02-17 23:13:50.431033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b78124fbad8'
down_revision: Union[str, Sequence[str], None] = 'f0993537e247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_check_time_only', 'check_results', ['checked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_check_time_only', table_name='check_results')
    # ### end Alembic commands ###
