"""misc model updates

Revision ID: cc0ddd888212
Revises: 4b78124fbad8
Create Date: 2026-02-18 01:09:57.325864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0ddd888212'
down_revision: Union[str, Sequence[str], None] = '4b78124fbad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'url',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
